// Code generated by MockGen. DO NOT EDIT.
// Source: curiosity/internal/pkg/content/usecase (interfaces: CPostRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "curiosity/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCPostRepository is a mock of CPostRepository interface.
type MockCPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCPostRepositoryMockRecorder
}

// MockCPostRepositoryMockRecorder is the mock recorder for MockCPostRepository.
type MockCPostRepositoryMockRecorder struct {
	mock *MockCPostRepository
}

// NewMockCPostRepository creates a new mock instance.
func NewMockCPostRepository(ctrl *gomock.Controller) *MockCPostRepository {
	mock := &MockCPostRepository{ctrl: ctrl}
	mock.recorder = &MockCPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPostRepository) EXPECT() *MockCPostRepositoryMockRecorder {
	return m.recorder
}

// GetPostByID mocks base method.
func (m *MockCPostRepository) GetPostByID(arg0 context.Context, arg1 int) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", arg0, arg1)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockCPostRepositoryMockRecorder) GetPostByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockCPostRepository)(nil).GetPostByID), arg0, arg1)
}
