type Post {
    id: Int!
    author: Int!
    title: String!
    content: String!
    is_commentable: Boolean!
    created_at: String!
}

type Comment {
    id: Int!
    author: Int!
    message: String!
    post: Int!
    parent: Int!
    depth: Int!
    path: String!
    replies: Int!
    created_at: String!
}

type User {
    id: Int!,
    username: String!,
    password: String!
}

type CommentNode {
    comment: Comment!
    children: [CommentNode!]!
}

input NewPost {
    title: String!
    content: String!
    author: Int!
    is_commentable: Boolean!
}
input NewComment {
    message: String!
    post: Int!
    parent: Int!
    author: Int!
}

input NewUser {
    username: String!
    password: String!
}

type Query {
    posts: [Post!]!
    postComments(postID: Int!, limit: Int!, offset: Int!): [Comment!]!
    replyComments(rootID: Int!): [Comment!]!
}

type Mutation {
    createPost(input: NewPost!): Int!
    createComment(input: NewComment!): Int!
    signUp(input: NewUser!): Int!
    signIn(input: NewUser!): Int!
}



