// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int32  `json:"id"`
	Author    int32  `json:"author"`
	Message   string `json:"message"`
	Post      int32  `json:"post"`
	Parent    int32  `json:"parent"`
	Depth     int32  `json:"depth"`
	Path      string `json:"path"`
	Replies   int32  `json:"replies"`
	CreatedAt string `json:"created_at"`
}

type CommentNode struct {
	Comment  *Comment       `json:"comment"`
	Children []*CommentNode `json:"children"`
}

type Mutation struct {
}

type NewComment struct {
	Message string `json:"message"`
	Post    int32  `json:"post"`
	Parent  int32  `json:"parent"`
	Author  int32  `json:"author"`
}

type NewPost struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        int32  `json:"author"`
	IsCommentable bool   `json:"is_commentable"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID            int32  `json:"id"`
	Author        int32  `json:"author"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	IsCommentable bool   `json:"is_commentable"`
}

type Query struct {
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
