// Code generated by MockGen. DO NOT EDIT.
// Source: curiosity/internal/pkg/content/repo/inmemory (interfaces: CommentCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "curiosity/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommentCache is a mock of CommentCache interface.
type MockCommentCache struct {
	ctrl     *gomock.Controller
	recorder *MockCommentCacheMockRecorder
}

// MockCommentCacheMockRecorder is the mock recorder for MockCommentCache.
type MockCommentCacheMockRecorder struct {
	mock *MockCommentCache
}

// NewMockCommentCache creates a new mock instance.
func NewMockCommentCache(ctrl *gomock.Controller) *MockCommentCache {
	mock := &MockCommentCache{ctrl: ctrl}
	mock.recorder = &MockCommentCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentCache) EXPECT() *MockCommentCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCommentCache) Get(arg0 int) (models.Comment, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(models.Comment)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommentCacheMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommentCache)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockCommentCache) GetAll() []models.Comment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Comment)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCommentCacheMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCommentCache)(nil).GetAll))
}

// Set mocks base method.
func (m *MockCommentCache) Set(arg0 int, arg1 models.Comment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1)
}

// Set indicates an expected call of Set.
func (mr *MockCommentCacheMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCommentCache)(nil).Set), arg0, arg1)
}
