// Code generated by MockGen. DO NOT EDIT.
// Source: curiosity/internal/pkg/content/repo/inmemory (interfaces: PostCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "curiosity/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostCache is a mock of PostCache interface.
type MockPostCache struct {
	ctrl     *gomock.Controller
	recorder *MockPostCacheMockRecorder
}

// MockPostCacheMockRecorder is the mock recorder for MockPostCache.
type MockPostCacheMockRecorder struct {
	mock *MockPostCache
}

// NewMockPostCache creates a new mock instance.
func NewMockPostCache(ctrl *gomock.Controller) *MockPostCache {
	mock := &MockPostCache{ctrl: ctrl}
	mock.recorder = &MockPostCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostCache) EXPECT() *MockPostCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPostCache) Get(arg0 int) (models.Post, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostCacheMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostCache)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockPostCache) GetAll() []models.Post {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Post)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPostCacheMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPostCache)(nil).GetAll))
}

// Set mocks base method.
func (m *MockPostCache) Set(arg0 int, arg1 models.Post) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1)
}

// Set indicates an expected call of Set.
func (mr *MockPostCacheMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPostCache)(nil).Set), arg0, arg1)
}
